/**
 * GitHub Branch + PR Push — Phase 5 §1.7 / §4.6
 *
 * §1.7 critical rule: NEVER push directly to main.
 * Every AI change set flows through a feature branch + PR.
 *
 * Branch naming: ai/<chatId-short>-<slug-of-prompt>
 * One branch per chat — subsequent prompts amend + update the same PR.
 *
 * v6.1 fixes (May 2026):
 *   FIX-P1 — All file changes for one prompt now land in a SINGLE commit
 *            via `commitTreeChangeSet` (git data API). The old per-file
 *            `createOrUpdateFileContents` loop produced one commit per
 *            file, which (a) bloated the PR timeline, (b) tripled the API
 *            usage budget for any non-trivial change, and (c) opened a
 *            race window where the 5th file's SHA could go stale because
 *            the 4th file's commit had already moved branch HEAD.
 *   FIX-P2 — `ensureBranch` no longer resets the branch on every push,
 *            so subsequent prompts in the same chat actually amend the PR
 *            (which PRD §1.7 promises).
 *   FIX-P3 — Slugify now trims trailing hyphens *after* the length cap,
 *            so a 39-char slug ending in "-" doesn't ship as "branch--".
 *   FIX-P4 — Empty change set now no-ops cleanly instead of opening an
 *            empty PR.
 *   FIX-P5 — Branch name length capped at 90 chars total (chat prefix +
 *            slug + separators). GitHub allows 250 but anything past 90
 *            wraps badly in the PR UI.
 */

import type { SearchReplaceBlock } from '@/lib/diff/parser';
import type { SandboxResult } from '@/lib/sandbox/types';
import {
  getOctokit,
  getBranchSHA,
  ensureBranch,
  commitTreeChangeSet,
} from './octokit';

export interface ChangedFile {
  path: string;
  content: string;
}

export interface PRRecord {
  prNumber: number;
  prUrl: string;
  branch: string;
  commitSha: string;
  previewUrl?: string;
}

export interface PushOptions {
  githubToken: string;
  owner: string;
  repo: string;
  defaultBranch: string;
  chatId: string;
  userPrompt: string;
  changedFiles: ChangedFile[];
  diffs: SearchReplaceBlock[];
  sandboxResult?: SandboxResult;
  /** Pass existing PR number to update instead of create */
  existingPRNumber?: number;
  agentSummary?: string;
}

/** Slugify a prompt for branch name — alphanumeric + hyphens, max 40 chars */
function slugify(text: string, max = 40): string {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, max);
  // FIX-P3 — trim trailing hyphen left over from the slice
  return slug.replace(/-+$/g, '') || 'change';
}

/** Build PR body from PRD §1.7 template */
function buildPRBody(opts: {
  prompt: string;
  changedFiles: ChangedFile[];
  diffs: SearchReplaceBlock[];
  sandboxResult?: SandboxResult;
  agentSummary?: string;
}): string {
  const { prompt, changedFiles, diffs, sandboxResult, agentSummary } = opts;

  const fileList = changedFiles
    .map((f) => {
      const diff = diffs.find((d) => d.filePath === f.path);
      const note = diff ? `— ${diff.replace.split('\n').length} line(s) changed` : '';
      return `- \`${f.path}\` ${note}`;
    })
    .join('\n');

  const sandboxLine = sandboxResult
    ? sandboxResult.ok
      ? `✅ Sandbox passed (${sandboxResult.mode}) in ${sandboxResult.durationMs}ms`
      : `❌ Sandbox errors — auto-heal attempted`
    : '⚠️ Sandbox verification skipped';

  return [
    '## AI Agent Studio — auto-generated change',
    '',
    `**Prompt**: "${prompt}"`,
    '',
    `**Files changed** (${changedFiles.length}):`,
    fileList,
    '',
    `**Sandbox verification**: ${sandboxLine}`,
    '',
    agentSummary ? `**Agent notes**: ${agentSummary}` : '',
    '',
    '---',
    '*Generated by [AI Agent Studio](https://github.com/ail-dev/ai-agent-studio)*',
  ]
    .filter((l) => l !== null && l !== undefined)
    .join('\n');
}

/**
 * Push a change set to a feature branch and open/update a PR.
 * Returns the PR record for storing in Dexie.
 *
 * §1.7 conflict handling:
 *   If the branch ref moves under us (concurrent push), `commitTreeChangeSet`
 *   throws a 422; the caller should rebuild blueprint and re-run Reviewer
 *   before retrying.
 */
export async function pushChangeSet(opts: PushOptions): Promise<PRRecord> {
  const {
    githubToken,
    owner,
    repo,
    defaultBranch,
    chatId,
    userPrompt,
    changedFiles,
    diffs,
    sandboxResult,
    existingPRNumber,
    agentSummary,
  } = opts;

  // FIX-P4 — guard against empty change sets
  if (changedFiles.length === 0) {
    throw new Error('pushChangeSet: no files in change set');
  }

  const octokit = getOctokit(githubToken);

  // FIX-P5 — cap total branch name
  const chatPrefix = chatId.slice(0, 7);
  const slugMax = Math.max(20, 90 - `ai/${chatPrefix}-`.length);
  const branch = `ai/${chatPrefix}-${slugify(userPrompt, slugMax)}`;

  // 1. Get latest default branch SHA
  const latestSHA = await getBranchSHA(githubToken, owner, repo, defaultBranch);

  // 2. Ensure our AI branch exists (or create it). FIX-P2 — does NOT reset
  //    an existing branch, so prior AI commits accumulate.
  await ensureBranch(githubToken, owner, repo, branch, latestSHA);

  // 3. Single batched commit for all file changes — FIX-P1
  const truncatedPrompt = userPrompt.slice(0, 70);
  const commitMessage =
    changedFiles.length === 1
      ? `ai: ${truncatedPrompt} — update ${changedFiles[0].path}`
      : `ai: ${truncatedPrompt} — ${changedFiles.length} files`;

  const { commitSha } = await commitTreeChangeSet(
    githubToken,
    owner,
    repo,
    branch,
    changedFiles.map((f) => ({ path: f.path, content: f.content })),
    commitMessage
  );

  // 4. Build PR body
  const body = buildPRBody({
    prompt: userPrompt,
    changedFiles,
    diffs,
    sandboxResult,
    agentSummary,
  });
  const title = `AI: ${userPrompt.slice(0, 72)}`;

  // 5. Open or update PR
  if (existingPRNumber) {
    await octokit.pulls.update({
      owner,
      repo,
      pull_number: existingPRNumber,
      body,
      title,
    });
    const { data: pr } = await octokit.pulls.get({
      owner,
      repo,
      pull_number: existingPRNumber,
    });
    return {
      prNumber: pr.number,
      prUrl: pr.html_url,
      branch,
      commitSha,
    };
  }

  // Find existing open PR for this branch
  const { data: existing } = await octokit.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: 'open',
  });

  if (existing.length > 0) {
    const pr = existing[0];
    await octokit.pulls.update({
      owner,
      repo,
      pull_number: pr.number,
      body,
      title,
    });
    return { prNumber: pr.number, prUrl: pr.html_url, branch, commitSha };
  }

  // Create new PR
  const { data: newPR } = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base: defaultBranch,
    title,
    body,
    draft: false,
  });

  return {
    prNumber: newPR.number,
    prUrl: newPR.html_url,
    branch,
    commitSha,
  };
}

/**
 * Delete the verify branch used for cloud-mode sandbox.
 * Best-effort — don't throw on failure.
 */
export async function deleteVerifyBranch(
  githubToken: string,
  owner: string,
  repo: string,
  branch: string
): Promise<void> {
  try {
    const octokit = getOctokit(githubToken);
    await octokit.git.deleteRef({ owner, repo, ref: `heads/${branch}` });
  } catch {
    // ignore
  }
}

/**
 * Upload a single file to the connected GitHub repo on the default branch.
 * Used by the "Upload to GitHub" button in FileExplorer.
 *
 * Creates a commit directly on defaultBranch (no feature branch) because
 * this is a manual, user-initiated, single-file publish action — not an
 * AI-generated change set.
 */
export async function uploadSingleFile(opts: {
  githubToken: string;
  owner: string;
  repo: string;
  defaultBranch: string;
  filePath: string;
  fileContent: string;
  commitMessage?: string;
}): Promise<{ commitSha: string; fileUrl: string }> {
  const { githubToken, owner, repo, defaultBranch, filePath, fileContent, commitMessage } = opts;

  const message = commitMessage ?? `chore: upload ${filePath} via AI Agent Studio`;

  const { commitSha } = await commitTreeChangeSet(
    githubToken,
    owner,
    repo,
    defaultBranch,
    [{ path: filePath, content: fileContent }],
    message
  );

  const fileUrl = `https://github.com/${owner}/${repo}/blob/${defaultBranch}/${filePath}`;
  return { commitSha, fileUrl };
}
