/**
 * GitHub Branch + PR Push — Phase 5 §1.7 / §4.6
 *
 * §1.7 critical rule: NEVER push directly to main.
 * Every AI change set flows through a feature branch + PR.
 *
 * Branch naming: ai/<chatId-short>-<slug-of-prompt>
 * One branch per chat — subsequent prompts amend + update the same PR.
 */

import type { SearchReplaceBlock } from '@/lib/diff/parser';
import type { SandboxResult } from '@/lib/sandbox/types';
import {
  getOctokit,
  getBranchSHA,
  ensureBranch,
  getFileSHA,
} from './octokit';

export interface ChangedFile {
  path: string;
  content: string;
}

export interface PRRecord {
  prNumber: number;
  prUrl: string;
  branch: string;
  previewUrl?: string;
}

export interface PushOptions {
  githubToken: string;
  owner: string;
  repo: string;
  defaultBranch: string;
  chatId: string;
  userPrompt: string;
  changedFiles: ChangedFile[];
  diffs: SearchReplaceBlock[];
  sandboxResult?: SandboxResult;
  /** Pass existing PR number to update instead of create */
  existingPRNumber?: number;
  agentSummary?: string;
}

/** Slugify a prompt for branch name — alphanumeric + hyphens, max 40 chars */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
}

/** Build PR body from PRD §1.7 template */
function buildPRBody(opts: {
  prompt: string;
  changedFiles: ChangedFile[];
  diffs: SearchReplaceBlock[];
  sandboxResult?: SandboxResult;
  agentSummary?: string;
}): string {
  const { prompt, changedFiles, diffs, sandboxResult, agentSummary } = opts;

  const fileList = changedFiles
    .map((f) => {
      const diff = diffs.find((d) => d.filePath === f.path);
      const note = diff ? `— ${diff.replace.split('\n').length} line(s) changed` : '';
      return `- \`${f.path}\` ${note}`;
    })
    .join('\n');

  const sandboxLine = sandboxResult
    ? sandboxResult.ok
      ? `✅ Sandbox passed (${sandboxResult.mode}) in ${sandboxResult.durationMs}ms`
      : `❌ Sandbox errors — auto-heal attempted`
    : '⚠️ Sandbox verification skipped';

  return [
    '## AI Agent Studio — auto-generated change',
    '',
    `**Prompt**: "${prompt}"`,
    '',
    `**Files changed** (${changedFiles.length}):`,
    fileList,
    '',
    `**Sandbox verification**: ${sandboxLine}`,
    '',
    agentSummary ? `**Agent notes**: ${agentSummary}` : '',
    '',
    '---',
    '*Generated by [AI Agent Studio](https://github.com/ail-dev/ai-agent-studio)*',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

/**
 * Push a change set to a feature branch and open/update a PR.
 * Returns the PR record for storing in Dexie.
 *
 * §1.7 conflict handling:
 *   If non-fast-forward push detected → caller should rebuild blueprint
 *   and re-run Reviewer before retrying.
 */
export async function pushChangeSet(opts: PushOptions): Promise<PRRecord> {
  const {
    githubToken,
    owner,
    repo,
    defaultBranch,
    chatId,
    userPrompt,
    changedFiles,
    diffs,
    sandboxResult,
    existingPRNumber,
    agentSummary,
  } = opts;

  const octokit = getOctokit(githubToken);
  const branch = `ai/${chatId.slice(0, 7)}-${slugify(userPrompt)}`;

  // 1. Get latest default branch SHA
  const latestSHA = await getBranchSHA(githubToken, owner, repo, defaultBranch);

  // 2. Ensure our AI branch exists (or create it)
  await ensureBranch(githubToken, owner, repo, branch, latestSHA);

  // 3. Push each changed file
  for (const file of changedFiles) {
    const existingSHA = await getFileSHA(githubToken, owner, repo, file.path, branch);
    const encoded = btoa(unescape(encodeURIComponent(file.content)));

    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: `ai: ${userPrompt.slice(0, 60)} — update ${file.path}`,
      content: encoded,
      branch,
      ...(existingSHA ? { sha: existingSHA } : {}),
    });
  }

  // 4. Build PR body
  const body = buildPRBody({ prompt: userPrompt, changedFiles, diffs, sandboxResult, agentSummary });
  const title = `AI: ${userPrompt.slice(0, 72)}`;

  // 5. Open or update PR
  if (existingPRNumber) {
    await octokit.pulls.update({
      owner,
      repo,
      pull_number: existingPRNumber,
      body,
      title,
    });
    const { data: pr } = await octokit.pulls.get({ owner, repo, pull_number: existingPRNumber });
    return {
      prNumber: pr.number,
      prUrl: pr.html_url,
      branch,
    };
  }

  // Find existing open PR for this branch
  const { data: existing } = await octokit.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: 'open',
  });

  if (existing.length > 0) {
    const pr = existing[0];
    await octokit.pulls.update({ owner, repo, pull_number: pr.number, body, title });
    return { prNumber: pr.number, prUrl: pr.html_url, branch };
  }

  // Create new PR
  const { data: newPR } = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base: defaultBranch,
    title,
    body,
    draft: false,
  });

  return {
    prNumber: newPR.number,
    prUrl: newPR.html_url,
    branch,
  };
}

/**
 * Delete the verify branch used for cloud-mode sandbox.
 * Best-effort — don't throw on failure.
 */
export async function deleteVerifyBranch(
  githubToken: string,
  owner: string,
  repo: string,
  branch: string
): Promise<void> {
  try {
    const octokit = getOctokit(githubToken);
    await octokit.git.deleteRef({ owner, repo, ref: `heads/${branch}` });
  } catch {
    // ignore
  }
}
